# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 99
    schedule:
      interval: "monthly"
    groups:
      deps-angular:
        patterns:
          - "@angular/*"
        update-types:
          - "minor"
          - "patch"
      deps-typescript:
        patterns:
          - "ts-*"
          - "tslib"
          - "tslint"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      deps-testing:
        patterns:
          - "karma*"
          - "karma-*"
          - "jasmine-*"
          - "@types/jasmine*"
      deps-webcomponents:
        patterns:
          - "@webcomponents/*"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 99
    schedule:
      interval: "daily"
