name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # - node-version: 12
          #   experimental: true
          - node-version: 14
            experimental: false
          - node-version: 16
            experimental: false
          - node-version: 18
            experimental: true
          - node-version: 20
            experimental: true
          - node-version: 22
            experimental: true
          # - node-version: 24
          #   experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v6

    - name: Cache node modules
      uses: actions/cache@v5
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      # continue-on-error: ${{ matrix.experimental }}
      run: |
        # Only set legacy OpenSSL provider for Node.js 18+
        if [ "${{ matrix.node-version }}" -ge 18 ]; then
          export NODE_OPTIONS="--openssl-legacy-provider"
        fi

        npm i
        npm run build:elements-prod

    - name: Archive build
      if: ${{ success() && matrix.node-version == 14 }}
      uses: actions/upload-artifact@v6
      with:
        name: build-artifact
        path: dist

    - name: Last step
      if: always()
      # continue-on-error: ${{ matrix.experimental }}
      run: |
        echo "Last step to avoid the experimental job failures"
